#! /bin/bash

set -e


if [ $EUID -ne 0 ]; then
	echo "$(basename $0) must be run as root"
	exit 1
fi

if ! frzr-release > /dev/null; then
	echo "Not currently running a frzr deployment"
	exit 1
fi

DEPLOYMENT=$(frzr-release)

mount -o remount,rw /
btrfs property set -ts /frzr_root/deployments/${DEPLOYMENT} ro false
systemctl disable frzr-etc
systemctl stop avahi-daemon # required for next command
umount /etc
sed -i -e 's/,ro,/,rw,/' /etc/fstab

if [ -d /usr/var/lib/pacman/local ] && [ ! -d /var/lib/pacman/local ]; then
	mkdir -p /var/lib/pacman
	cp -r /usr/var/lib/pacman/local /var/lib/pacman/
fi

systemctl start avahi-daemon
echo "frzr deployment ${DEPLOYMENT} unlocked"
