#! /bin/bash

if [ $EUID -ne 0 ]; then
	echo "$(basename $0) must be run as root"
	exit 1
fi

MOUNT_PATH=$1
# Check device ID and see if any quirks exist
if [ -e "${MOUNT_PATH}"/etc/device-quirks/id-device ]; then
   ."${MOUNT_PATH}"/etc/device-quirks/id-device
else
   echo "Unable to run id-device to determine if quirks need to be applied"
   exit 0
fi
RESULT=$?
# Check RESULT and determine if we need to rebuild the initramfs
if [[ $RESULT == 0 ]]; then
   BOOT_CFG="${MOUNT_PATH}/boot/loader/entries/frzr.conf"
   if [ -f "${BOOT_CFG}" ]; then
	# When rebuilding initramfs we will have to use the standard location
	cp ${MOUNT_PATH}/boot/${DEPLOYMENT}/* ${MOUNT_PATH}/boot/
	sed -i ${BOOT_CFG} -e s,/${DEPLOYMENT}/,/,g
   fi
   mkinitcpio -P
else
   echo "initramfs did not need to be rebuilt"
fi
