#! /bin/bash

if [ $EUID -ne 0 ]; then
	echo "$(basename $0) must be run as root"
	exit 1
fi

# Check device ID and see if any quirks exist
if [ -e "${MOUNT_PATH}"/etc/device-quirks/id-device ]; then
   "${MOUNT_PATH}"/etc/device-quirks/./id-device
   RESULT=$?
else
   echo "Unable to run id-device to determine if quirks need to be applied"
   exit 0
fi

# Check RESULT and determine if we need to rebuild the initramfs
if [[ ${RESULT} == "0" ]]; then
   BOOT_CFG="${MOUNT_PATH}/boot/loader/entries/frzr.conf"
   if [ -f "${BOOT_CFG}" ]; then
	# When rebuilding initramfs we will have to use the standard location
	cp ${MOUNT_PATH}/boot/${DEPLOYMENT}/* ${MOUNT_PATH}/boot/
	sed -i ${BOOT_CFG} -e s,/${DEPLOYMENT}/,/,g
   fi
   # We may need to grab the /etc/mkinitcpio.conf from the deployed system to the installer media to build
   cp ${MOUNT_PATH}/etc/mkinitcpio.conf /etc/mkinitcpio.conf
   mkinitcpio -P
   
   # Once this is built we'll need to move it back to the deployed system
   cp /boot/initramfs-linux.img ${MOUNT_PATH}/boot/
   
else
   echo "initramfs did not need to be rebuilt"
fi
